(in-package #:tiny-brain/tests)

(defvar *failures* 0)

(defmacro check (form)
  `(unless ,form
     (incf *failures*)
     (format t "~&FAIL: ~S~%" ',form)))

(defun symbol-name= (left right)
  (and (symbolp left)
       (symbolp right)
       (string= (symbol-name left) (symbol-name right))))

(defun term= (left right)
  (cond
    ((and (consp left) (consp right))
     (and (term= (first left) (first right))
          (term= (rest left) (rest right))))
    ((or (consp left) (consp right))
     nil)
    ((and (symbolp left) (symbolp right))
     (symbol-name= left right))
    (t
     (eql left right))))

(defun test-observing-room-adds-visible-beliefs ()
  (let ((world (make-world))
        (agent (make-agent)))
    (observe agent world 'room-1)
    (check (why agent '(room room-1)))
    (check (why agent '(object ball-1)))
    (check (why agent '(color ball-1 red)))
    (check (why agent '(location ball-1 room-1)))))

(defun test-observing-room-does-not-reveal-closed-container-contents ()
  (let ((world (make-world))
        (agent (make-agent)))
    (observe agent world 'room-1)
    (check (why agent '(container box-1)))
    (check (member '(contents box-1) (agent-unknowns agent) :test #'term=))
    (check (not (why agent '(object key-1))))
    (check (not (why agent '(location key-1 box-1))))))

(defun test-beliefs-have-provenance ()
  (let ((world (make-world))
        (agent (make-agent)))
    (observe agent world 'room-1)
    (let ((belief (why agent '(color ball-1 red))))
      (check belief)
      (check (eql (belief-source belief) :direct-observation))
      (check (= (belief-confidence belief) 1.0))
      (check (integerp (belief-observed-at belief))))))

(defun test-infer-adds-derived-beliefs ()
  (let ((world (make-world))
        (agent (make-agent)))
    (observe agent world 'room-1)
    (check (not (why agent '(visible ball-1))))
    (infer agent)
    (check (why agent '(visible ball-1)))
    (check (why agent '(visible box-1)))
    (check (why agent '(object box-1)))))

(defun test-inferred-beliefs-explain-their-premises ()
  (let ((world (make-world))
        (agent (make-agent)))
    (observe agent world 'room-1)
    (infer agent)
    (let ((belief (why agent '(visible ball-1))))
      (check belief)
      (check (eql (belief-source belief) :inference))
      (check (eql (belief-rule belief) :thing-in-observed-room-is-visible))
      (check (member '(location ball-1 room-1)
                     (belief-premises belief)
                     :test #'term=))
      (check (member '(room room-1)
                     (belief-premises belief)
                     :test #'term=)))))

(defun test-inference-does-not-inspect-ground-truth ()
  (let ((world (make-world))
        (agent (make-agent)))
    (observe agent world 'room-1)
    (infer agent)
    (check (not (why agent '(object key-1))))
    (check (not (why agent '(location key-1 box-1))))
    (check (not (why agent '(location key-1 room-1))))))

(defun test-make-world-accepts-custom-facts ()
  (let ((world (make-world :facts '((room lab)
                                    (object sensor)
                                    (location sensor lab)))))
    (check (find '(room lab) (world-facts world) :test #'term=))
    (check (not (find '(room room-1) (world-facts world) :test #'term=)))))

(defun test-define-scenario-builds-scenario-record ()
  (let ((scenario (define-scenario lab-box
                    :facts ((room lab)
                            (container crate)
                            (closed crate)
                            (location crate lab))
                    :observations (lab)
                    :goals ((known (contents crate))))))
    (check (symbol-name= (scenario-name scenario) 'lab-box))
    (check (find '(room lab) (scenario-facts scenario) :test #'term=))
    (check (find 'lab (scenario-observations scenario) :test #'term=))
    (check (find '(known (contents crate))
                 (scenario-goals scenario)
                 :test #'term=))))

(defun test-start-scenario-initializes-agent-and-world ()
  (let ((scenario (define-scenario lab-box
                    :facts ((room lab)
                            (container crate)
                            (closed crate)
                            (location crate lab)
                            (object gem)
                            (location gem crate))
                    :observations (lab)
                    :goals ((known (contents crate)))
                    :hypotheses (((contents crate)
                                  (contents crate gem)
                                  0.8)
                                 ((contents crate)
                                  (contents crate empty)
                                  0.2)))))
    (multiple-value-bind (agent world returned-scenario)
        (start-scenario scenario)
      (check (eq returned-scenario scenario))
      (check (find '(object gem) (world-facts world) :test #'term=))
      (check (why agent '(container crate)))
      (check (why agent '(visible crate)))
      (check (member '(contents crate) (agent-unknowns agent) :test #'term=))
      (check (find '(known (contents crate))
                   (agent-goals agent)
                   :key #'goal-desire
                   :test #'term=))
      (check (= (length (agent-hypotheses agent)) 2))
      (check (eql (plan-status
                   (plan-for-goal agent '(known (contents crate))))
                  :ready)))))

(defun test-load-scenario-reads-example-file ()
  (let ((scenario (load-scenario "examples/kitchen-box.lisp")))
    (check (symbol-name= (scenario-name scenario) 'kitchen-box))
    (check (find '(room kitchen) (scenario-facts scenario) :test #'term=))
    (multiple-value-bind (agent world returned-scenario)
        (start-scenario scenario)
      (declare (ignore world))
      (check (eq returned-scenario scenario))
      (check (why agent '(container cabinet)))
      (check (eql (plan-status
                   (plan-for-goal agent '(known (contents cabinet))))
                  :ready)))))

(defun issue-code-present-p (code issues)
  (find code issues :key #'validation-issue-code))

(defun test-validate-scenario-accepts-example-file ()
  (let ((scenario (load-scenario "examples/kitchen-box.lisp")))
    (check (null (validate-scenario scenario)))
    (check (scenario-valid-p scenario))))

(defun test-validate-scenario-reports_unknown_observation ()
  (let* ((scenario (define-scenario bad-observation
                     :facts ((room lab))
                     :observations (missing-room)))
         (issues (validate-scenario scenario)))
    (check (not (scenario-valid-p scenario)))
    (check (issue-code-present-p :unknown-observation-target issues))))

(defun test-validate-scenario-reports_container_errors ()
  (let* ((scenario (define-scenario bad-containers
                     :facts ((room lab)
                             (closed crate)
                             (container box))
                     :observations (lab)))
         (issues (validate-scenario scenario)))
    (check (issue-code-present-p :closed-non-container issues))
    (check (issue-code-present-p :container-without-location issues))))

(defun test-validate-scenario-reports_goal_and_hypothesis_errors ()
  (let* ((scenario (define-scenario bad-goal-and-hypothesis
                     :facts ((room lab)
                             (container crate)
                             (location crate lab))
                     :observations (lab)
                     :goals ((known (contents missing-box)))
                     :hypotheses (((contents missing-box)
                                   (contents missing-box gem)
                                   0.5)
                                  ((contents crate)
                                   (contents other-box gem)
                                   0.5)
                                  ((contents crate)
                                   (contents crate gem)
                                   2.0))))
         (issues (validate-scenario scenario)))
    (check (issue-code-present-p :goal-unknown-container issues))
    (check (issue-code-present-p :hypothesis-unknown-container issues))
    (check (issue-code-present-p :hypothesis-question-mismatch issues))
    (check (issue-code-present-p :invalid-hypothesis issues))))

(defun test-show-validation-prints_issues ()
  (let* ((scenario (define-scenario bad-observation
                     :facts ((room lab))
                     :observations (missing-room)))
         (issues (validate-scenario scenario))
         (text (let ((*package* (find-package :tiny-brain)))
                 (with-output-to-string (stream)
                   (show-validation issues stream)))))
    (check (search "VALIDATION:" text))
    (check (search ":ERROR" text))
    (check (search ":UNKNOWN-OBSERVATION-TARGET" text))
    (check (search "MISSING-ROOM" text))))

(defun test-example-scenarios-have_expected_validation ()
  (dolist (pathname '("examples/kitchen-box.lisp"
                      "examples/lab-crate.lisp"
                      "examples/blocked-goal.lisp"
                      "examples/nested-containers.lisp"))
    (check (scenario-valid-p (load-scenario pathname))))
  (let ((issues (validate-scenario
                 (load-scenario "examples/invalid-scenario.lisp"))))
    (check (issue-code-present-p :unknown-observation-target issues))
    (check (issue-code-present-p :closed-non-container issues))
    (check (issue-code-present-p :invalid-hypothesis issues))))

(defun test-opening-container-requires-access ()
  (let ((world (make-world))
        (agent (make-agent)))
    (observe agent world 'room-1)
    (check (not (why agent '(visible box-1))))
    (check (handler-case
               (progn
                 (open-container agent world 'box-1)
                 nil)
             (error ()
               t)))))

(defun test-opening-container-reveals-immediate-contents ()
  (let ((world (make-world))
        (agent (make-agent)))
    (observe agent world 'room-1)
    (infer agent)
    (check (not (why agent '(object key-1))))
    (check (member '(contents box-1) (agent-unknowns agent) :test #'term=))
    (open-container agent world 'box-1)
    (check (why agent '(open box-1)))
    (check (not (why agent '(closed box-1))))
    (check (why agent '(object key-1)))
    (check (why agent '(color key-1 brass)))
    (check (why agent '(location key-1 box-1)))
    (check (not (member '(contents box-1)
                        (agent-unknowns agent)
                        :test #'term=)))))

(defun test-action-observations-have-provenance ()
  (let ((world (make-world))
        (agent (make-agent)))
    (observe agent world 'room-1)
    (infer agent)
    (open-container agent world 'box-1)
    (let ((belief (why agent '(object key-1))))
      (check belief)
      (check (eql (belief-source belief) :action-observation))
      (check (= (belief-confidence belief) 1.0)))))

(defun test-inference-after-opening-uses-new-beliefs ()
  (let ((world (make-world))
        (agent (make-agent)))
    (observe agent world 'room-1)
    (infer agent)
    (open-container agent world 'box-1)
    (check (not (why agent '(location key-1 room-1))))
    (infer agent)
    (let ((belief (why agent '(location key-1 room-1))))
      (check belief)
      (check (eql (belief-source belief) :inference))
      (check (eql (belief-rule belief) :location-through-container)))))

(defun test-suggest-actions-requires-believed-preconditions ()
  (let ((world (make-world))
        (agent (make-agent)))
    (observe agent world 'room-1)
    (check (null (suggest-actions agent)))
    (infer agent)
    (check (suggest-actions agent))))

(defun test-suggest-actions-identifies-unknown-reducing-action ()
  (let ((world (make-world))
        (agent (make-agent)))
    (observe agent world 'room-1)
    (infer agent)
    (let ((suggestions (suggest-actions agent)))
      (check (= (length suggestions) 1))
      (let ((suggestion (first suggestions)))
        (check (eql (action-suggestion-action suggestion) 'open-container))
        (check (symbol-name= (action-suggestion-target suggestion) 'box-1))
        (check (term= (action-suggestion-reason suggestion)
                      '(contents box-1)))
        (check (member '(visible box-1)
                       (action-suggestion-preconditions suggestion)
                       :test #'term=))))))

(defun test-suggest-actions-disappears-after-unknown-is-resolved ()
  (let ((world (make-world))
        (agent (make-agent)))
    (observe agent world 'room-1)
    (infer agent)
    (check (suggest-actions agent))
    (open-container agent world 'box-1)
    (check (null (suggest-actions agent)))))

(defun test-exclusive-state-beliefs-retract-conflicts ()
  (let ((agent (make-agent)))
    (add-belief agent '(closed box-1))
    (add-belief agent '(open box-1))
    (check (why agent '(open box-1)))
    (check (not (why agent '(closed box-1))))
    (check (= (length (agent-retractions agent)) 1))
    (let ((retraction (first (agent-retractions agent))))
      (check (term= (retraction-fact retraction) '(closed box-1)))
      (check (eql (retraction-reason retraction)
                  :replaced-by-exclusive-state))
      (check (term= (retraction-replaced-by retraction)
                    '(open box-1))))))

(defun test-exclusive-state-retraction-is-per-object ()
  (let ((agent (make-agent)))
    (add-belief agent '(closed box-1))
    (add-belief agent '(closed box-2))
    (add-belief agent '(open box-1))
    (check (why agent '(open box-1)))
    (check (not (why agent '(closed box-1))))
    (check (why agent '(closed box-2)))))

(defun test-opening-container-records-retraction ()
  (let ((world (make-world))
        (agent (make-agent)))
    (observe agent world 'room-1)
    (infer agent)
    (open-container agent world 'box-1)
    (check (why agent '(open box-1)))
    (check (not (why agent '(closed box-1))))
    (let ((retraction (first (agent-retractions agent))))
      (check retraction)
      (check (term= (retraction-fact retraction) '(closed box-1)))
      (check (term= (retraction-replaced-by retraction)
                    '(open box-1))))))

(defun test-explain-direct-observation ()
  (let ((world (make-world))
        (agent (make-agent)))
    (observe agent world 'room-1)
    (let ((explanation (explain agent '(color ball-1 red))))
      (check (term= (explanation-fact explanation)
                    '(color ball-1 red)))
      (check (eql (explanation-status explanation) :believed))
      (check (eql (explanation-source explanation) :direct-observation))
      (check (= (explanation-confidence explanation) 1.0))
      (check (null (explanation-premises explanation))))))

(defun test-explain-inference-chain ()
  (let ((world (make-world))
        (agent (make-agent)))
    (observe agent world 'room-1)
    (infer agent)
    (let ((explanation (explain agent '(visible ball-1))))
      (check (eql (explanation-status explanation) :believed))
      (check (eql (explanation-source explanation) :inference))
      (check (eql (explanation-rule explanation)
                  :thing-in-observed-room-is-visible))
      (check (= (length (explanation-premises explanation)) 2))
      (check (find '(location ball-1 room-1)
                   (explanation-premises explanation)
                   :key #'explanation-fact
                   :test #'term=))
      (check (find '(room room-1)
                   (explanation-premises explanation)
                   :key #'explanation-fact
                   :test #'term=)))))

(defun test-explain-retracted-belief ()
  (let ((agent (make-agent)))
    (add-belief agent '(closed box-1))
    (add-belief agent '(open box-1))
    (let ((explanation (explain agent '(closed box-1))))
      (check (eql (explanation-status explanation) :retracted))
      (check (term= (retraction-fact (explanation-retraction explanation))
                    '(closed box-1)))
      (check (term= (retraction-replaced-by
                     (explanation-retraction explanation))
                    '(open box-1))))))

(defun test-explain-unknown-fact ()
  (let ((agent (make-agent)))
    (let ((explanation (explain agent '(color missing-thing purple))))
      (check (term= (explanation-fact explanation)
                    '(color missing-thing purple)))
      (check (eql (explanation-status explanation) :unknown)))))

(defun test-add-goal-records-active-goal ()
  (let ((agent (make-agent)))
    (let ((goal (add-goal agent '(known (contents box-1)))))
      (check (term= (goal-desire goal) '(known (contents box-1))))
      (check (eql (goal-status goal) :active))
      (check (integerp (goal-created-at goal)))
      (check (member goal (agent-goals agent))))))

(defun test-known-fact-goal-is-satisfied-by-belief ()
  (let ((agent (make-agent)))
    (add-belief agent '(color ball-1 red))
    (let ((goal (add-goal agent '(known (color ball-1 red)))))
      (check (eql (goal-status goal) :satisfied))
      (check (integerp (goal-satisfied-at goal))))))

(defun test-contents-goal-is-satisfied-after-opening-container ()
  (let ((world (make-world))
        (agent (make-agent)))
    (observe agent world 'room-1)
    (infer agent)
    (let ((goal (add-goal agent '(known (contents box-1)))))
      (check (eql (goal-status goal) :active))
      (open-container agent world 'box-1)
      (check (eql (goal-status goal) :satisfied))
      (check (integerp (goal-satisfied-at goal))))))

(defun test-suggestion-can-serve-active-goal ()
  (let ((world (make-world))
        (agent (make-agent)))
    (observe agent world 'room-1)
    (infer agent)
    (let ((goal (add-goal agent '(known (contents box-1)))))
      (let ((suggestion (first (suggest-actions agent))))
        (check suggestion)
        (check (eq (action-suggestion-serves-goal suggestion) goal))))))

(defun test-remove-goal ()
  (let ((agent (make-agent)))
    (add-goal agent '(known (contents box-1)))
    (check (agent-goals agent))
    (remove-goal agent '(known (contents box-1)))
    (check (null (agent-goals agent)))))

(defun test-select-action-prefers-active-goal ()
  (let ((world (make-world))
        (agent (make-agent)))
    (observe agent world 'room-1)
    (infer agent)
    (let ((goal (add-goal agent '(known (contents box-1)))))
      (let ((selection (select-action agent)))
        (check selection)
        (check (eql (selected-action-reason selection)
                    :serves-active-goal))
        (check (eq (action-suggestion-serves-goal
                    (selected-action-suggestion selection))
                   goal))))))

(defun test-select-action-can-pick-curiosity-suggestion ()
  (let ((world (make-world))
        (agent (make-agent)))
    (observe agent world 'room-1)
    (infer agent)
    (let ((selection (select-action agent)))
      (check selection)
      (check (eql (selected-action-reason selection)
                  :reduces-unknown))
      (check (eql (action-suggestion-action
                   (selected-action-suggestion selection))
                  'open-container)))))

(defun test-perform-suggestion-executes-known-action ()
  (let ((world (make-world))
        (agent (make-agent)))
    (observe agent world 'room-1)
    (infer agent)
    (let ((goal (add-goal agent '(known (contents box-1)))))
      (let ((selection (select-action agent)))
        (perform-suggestion agent world (selected-action-suggestion selection))
        (check (why agent '(open box-1)))
        (check (why agent '(object key-1)))
        (check (eql (goal-status goal) :satisfied))))))

(defun test-select-action-returns-nil-without-suggestions ()
  (let ((agent (make-agent)))
    (check (null (select-action agent)))))

(defun test-plan-for-goal-ready-with-existing-goal ()
  (let ((world (make-world))
        (agent (make-agent)))
    (observe agent world 'room-1)
    (infer agent)
    (let ((goal (add-goal agent '(known (contents box-1)))))
      (let ((plan (plan-for-goal agent '(known (contents box-1)))))
        (check (eql (plan-status plan) :ready))
        (check (eql (plan-reason plan) :one-step-suggestion))
        (check (term= (plan-goal plan) '(known (contents box-1))))
        (check (= (length (plan-steps plan)) 1))
        (check (eq (action-suggestion-serves-goal
                    (first (plan-steps plan)))
                   goal))
        (check (eql (action-suggestion-action (first (plan-steps plan)))
                    'open-container))))))

(defun test-plan-for-goal-ready-without-existing-goal ()
  (let ((world (make-world))
        (agent (make-agent)))
    (observe agent world 'room-1)
    (infer agent)
    (let ((plan (plan-for-goal agent '(known (contents box-1)))))
      (check (eql (plan-status plan) :ready))
      (check (= (length (plan-steps plan)) 1))
      (check (eql (action-suggestion-action (first (plan-steps plan)))
                  'open-container)))))

(defun test-plan-for-goal-satisfied ()
  (let ((agent (make-agent)))
    (add-belief agent '(color ball-1 red))
    (let ((plan (plan-for-goal agent '(known (color ball-1 red)))))
      (check (eql (plan-status plan) :satisfied))
      (check (null (plan-steps plan)))
      (check (eql (plan-reason plan) :goal-already-satisfied)))))

(defun test-plan-for-goal-blocked-without-suggestion ()
  (let ((world (make-world))
        (agent (make-agent)))
    (observe agent world 'room-1)
    (let ((plan (plan-for-goal agent '(known (contents box-1)))))
      (check (eql (plan-status plan) :blocked))
      (check (null (plan-steps plan)))
      (check (eql (plan-reason plan) :no-available-suggestion)))))

(defun test-show-plan-prints-inspectable-plan ()
  (let ((world (make-world))
        (agent (make-agent)))
    (observe agent world 'room-1)
    (infer agent)
    (let* ((plan (plan-for-goal agent '(known (contents box-1))))
           (text (let ((*package* (find-package :tiny-brain)))
                   (with-output-to-string (stream)
                     (show-plan plan stream)))))
      (check (search "PLAN:" text))
      (check (search "STATUS: :READY" text))
      (check (search "OPEN-CONTAINER" text))
      (check (search "BOX-1" text)))))

(defun test-step-agent-acts-on-ready-scenario-goal ()
  (let ((scenario (load-scenario "examples/kitchen-box.lisp")))
    (multiple-value-bind (agent world)
        (start-scenario scenario)
      (let ((trace (step-agent agent world)))
        (check (eql (step-trace-status trace) :acted))
        (check (term= (step-trace-goal trace)
                      '(known (contents cabinet))))
        (check (term= (step-trace-action trace)
                      '(open-container cabinet)))
        (check (member '(contents cabinet)
                       (step-trace-resolved-unknowns trace)
                       :test #'term=))
        (check (member '(open cabinet)
                       (step-trace-new-beliefs trace)
                       :test #'term=))
        (check (why agent '(object mug)))
        (check (eql (goal-status (first (agent-goals agent)))
                    :satisfied))))))

(defun test-step-agent-reports-satisfied-goal ()
  (let ((agent (make-agent))
        (world (make-world)))
    (add-belief agent '(color ball-1 red))
    (add-goal agent '(known (color ball-1 red)))
    (let ((trace (step-agent agent world)))
      (check (eql (step-trace-status trace) :satisfied))
      (check (term= (step-trace-goal trace)
                    '(known (color ball-1 red))))
      (check (null (step-trace-action trace))))))

(defun test-step-agent-reports-blocked-goal ()
  (let ((agent (make-agent))
        (world (make-world)))
    (add-goal agent '(known (contents missing-box)))
    (let ((trace (step-agent agent world)))
      (check (eql (step-trace-status trace) :blocked))
      (check (eql (step-trace-reason trace) :no-available-suggestion))
      (check (null (step-trace-action trace))))))

(defun test-step-agent-observes_unobserved_room_for_contents_goal ()
  (let ((scenario (load-scenario "examples/blocked-goal.lisp")))
    (multiple-value-bind (agent world)
        (start-scenario scenario)
      (let ((trace (step-agent agent world)))
        (check (eql (step-trace-status trace) :acted))
        (check (term= (step-trace-action trace)
                      '(observe-room storage)))
        (check (why agent '(container safe)))
        (check (member '(contents safe)
                       (agent-unknowns agent)
                       :test #'term=))))))

(defun test-step-agent-can_satisfy_goal_after_observing_remote_room ()
  (let ((scenario (load-scenario "examples/blocked-goal.lisp")))
    (multiple-value-bind (agent world)
        (start-scenario scenario)
      (let ((first-trace (step-agent agent world))
            (second-trace (step-agent agent world))
            (third-trace (step-agent agent world)))
        (check (term= (step-trace-action first-trace)
                      '(observe-room storage)))
        (check (term= (step-trace-action second-trace)
                      '(open-container safe)))
        (check (eql (step-trace-status third-trace) :satisfied))
        (check (eql (goal-status (first (agent-goals agent)))
                    :satisfied))))))

(defun test-step-agent-can-act-from-curiosity-without-goal ()
  (let ((world (make-world))
        (agent (make-agent)))
    (observe agent world 'room-1)
    (infer agent)
    (let ((trace (step-agent agent world)))
      (check (eql (step-trace-status trace) :acted))
      (check (null (step-trace-goal trace)))
      (check (term= (step-trace-action trace)
                    '(open-container box-1))))))

(defun test-show-trace-prints-step_summary ()
  (let ((scenario (load-scenario "examples/kitchen-box.lisp")))
    (multiple-value-bind (agent world)
        (start-scenario scenario)
      (let* ((trace (step-agent agent world))
             (text (let ((*package* (find-package :tiny-brain)))
                     (with-output-to-string (stream)
                       (show-trace trace stream)))))
        (check (search "STEP: :ACTED" text))
        (check (search "ACTION: (OPEN-CONTAINER CABINET)" text))
        (check (search "NEW BELIEFS:" text))
        (check (search "RESOLVED UNKNOWNS:" text))
        (check (search "CONTENTS" text))))))

(defun test-show-cognition-prints_brain_centered_cycle ()
  (let ((scenario (load-scenario "examples/kitchen-box.lisp")))
    (multiple-value-bind (agent world)
        (start-scenario scenario)
      (let* ((trace (step-agent agent world))
             (text (let ((*package* (find-package :tiny-brain)))
                     (with-output-to-string (stream)
                       (show-cognition agent trace stream)))))
        (check (search "COGNITIVE CYCLE:" text))
        (check (search "PERCEPTION:" text))
        (check (search "WORKING MEMORY:" text))
        (check (search "SEMANTIC MEMORY:" text))
        (check (search "CURIOSITY:" text))
        (check (search "PLAN:" text))
        (check (search "ACTION:" text))
        (check (search "LEARNING:" text))
        (check (search "EPISODIC MEMORY:" text))
        (check (search "OPEN-CONTAINER" text))
        (check (search "MUG" text))))))

(defun test-observe-records-episode ()
  (let ((world (make-world))
        (agent (make-agent)))
    (observe agent world 'room-1)
    (check (= (length (agent-episodes agent)) 1))
    (let ((episode (first (agent-episodes agent))))
      (check (eql (episode-type episode) :observation))
      (check (term= (episode-detail episode) '(observe room-1)))
      (check (member '(room room-1)
                     (episode-results episode)
                     :test #'term=))
      (check (member '(color ball-1 red)
                     (episode-results episode)
                     :test #'term=))
      (check (integerp (episode-time episode))))))

(defun test-open-container-records-action-episode ()
  (let ((world (make-world))
        (agent (make-agent)))
    (observe agent world 'room-1)
    (infer agent)
    (open-container agent world 'box-1)
    (check (= (length (agent-episodes agent)) 2))
    (let ((episode (first (agent-episodes agent))))
      (check (eql (episode-type episode) :action))
      (check (term= (episode-detail episode) '(open-container box-1)))
      (check (member '(open box-1)
                     (episode-results episode)
                     :test #'term=))
      (check (member '(object key-1)
                     (episode-results episode)
                     :test #'term=)))))

(defun test-infer-does-not-record-episode-yet ()
  (let ((world (make-world))
        (agent (make-agent)))
    (observe agent world 'room-1)
    (infer agent)
    (check (= (length (agent-episodes agent)) 1))))

(defun test-add-hypothesis-records-explicit-uncertainty ()
  (let ((agent (make-agent)))
    (let ((hypothesis (add-hypothesis agent
                                      '(contents box-1)
                                      '(contents box-1 key-1)
                                      0.7)))
      (check (term= (hypothesis-question hypothesis)
                    '(contents box-1)))
      (check (term= (hypothesis-proposition hypothesis)
                    '(contents box-1 key-1)))
      (check (= (hypothesis-confidence hypothesis) 0.7))
      (check (eql (hypothesis-source hypothesis) :manual))
      (check (eql (hypothesis-status hypothesis) :active))
      (check (member hypothesis (agent-hypotheses agent))))))

(defun test-hypotheses-are-not-beliefs ()
  (let ((agent (make-agent)))
    (add-hypothesis agent
                    '(contents box-1)
                    '(contents box-1 key-1)
                    0.7)
    (check (not (why agent '(contents box-1 key-1))))
    (check (not (why agent '(location key-1 box-1))))))

(defun test-opening-container-confirms-compatible-hypothesis ()
  (let ((world (make-world))
        (agent (make-agent)))
    (observe agent world 'room-1)
    (infer agent)
    (let ((key-hypothesis (add-hypothesis agent
                                          '(contents box-1)
                                          '(contents box-1 key-1)
                                          0.7))
          (empty-hypothesis (add-hypothesis agent
                                            '(contents box-1)
                                            '(contents box-1 empty)
                                            0.2))
          (unknown-hypothesis (add-hypothesis agent
                                              '(contents box-1)
                                              '(contents box-1 unknown)
                                              0.1)))
      (open-container agent world 'box-1)
      (check (eql (hypothesis-status key-hypothesis) :confirmed))
      (check (integerp (hypothesis-resolved-at key-hypothesis)))
      (check (eql (hypothesis-status empty-hypothesis) :rejected))
      (check (eql (hypothesis-status unknown-hypothesis) :rejected)))))

(defun test-hypothesis-added_after_observation_can_resolve_immediately ()
  (let ((world (make-world))
        (agent (make-agent)))
    (observe agent world 'room-1)
    (infer agent)
    (open-container agent world 'box-1)
    (let ((hypothesis (add-hypothesis agent
                                      '(contents box-1)
                                      '(contents box-1 key-1)
                                      0.7)))
      (check (eql (hypothesis-status hypothesis) :confirmed)))))

(defun test-suggest-tests-identifies_hypothesis_distinguishing_action ()
  (let ((world (make-world))
        (agent (make-agent)))
    (observe agent world 'room-1)
    (infer agent)
    (add-hypothesis agent '(contents box-1) '(contents box-1 key-1) 0.7)
    (add-hypothesis agent '(contents box-1) '(contents box-1 empty) 0.2)
    (let ((suggestions (suggest-tests agent)))
      (check (= (length suggestions) 1))
      (let ((suggestion (first suggestions)))
        (check (eql (action-suggestion-action suggestion) 'open-container))
        (check (term= (action-suggestion-tests-question suggestion)
                      '(contents box-1)))))))

(defun test-suggest-tests_requires_competing_active_hypotheses ()
  (let ((world (make-world))
        (agent (make-agent)))
    (observe agent world 'room-1)
    (infer agent)
    (add-hypothesis agent '(contents box-1) '(contents box-1 key-1) 0.7)
    (check (null (suggest-tests agent)))))

(defun test-select-action-prefers_goal_and_hypothesis_test ()
  (let ((world (make-world))
        (agent (make-agent)))
    (observe agent world 'room-1)
    (infer agent)
    (add-goal agent '(known (contents box-1)))
    (add-hypothesis agent '(contents box-1) '(contents box-1 key-1) 0.7)
    (add-hypothesis agent '(contents box-1) '(contents box-1 empty) 0.2)
    (let ((selection (select-action agent)))
      (check selection)
      (check (eql (selected-action-reason selection)
                  :serves-active-goal-and-tests-hypotheses))
      (check (term= (action-suggestion-tests-question
                     (selected-action-suggestion selection))
                    '(contents box-1))))))

(defun test-select-action-can_prefer_hypothesis_test_without_goal ()
  (let ((world (make-world))
        (agent (make-agent)))
    (observe agent world 'room-1)
    (infer agent)
    (add-hypothesis agent '(contents box-1) '(contents box-1 key-1) 0.7)
    (add-hypothesis agent '(contents box-1) '(contents box-1 empty) 0.2)
    (let ((selection (select-action agent)))
      (check selection)
      (check (eql (selected-action-reason selection)
                  :tests-hypotheses)))))

(defun test-show-memory-groups-current_agent_state ()
  (let ((world (make-world))
        (agent (make-agent)))
    (observe agent world 'room-1)
    (infer agent)
    (add-goal agent '(known (contents box-1)))
    (add-hypothesis agent '(contents box-1) '(contents box-1 key-1) 0.7)
    (add-hypothesis agent '(contents box-1) '(contents box-1 empty) 0.2)
    (let ((text (let ((*package* (find-package :tiny-brain)))
                  (with-output-to-string (stream)
                    (show-memory agent stream)))))
      (check (search "WORKING MEMORY:" text))
      (check (search "SEMANTIC MEMORY:" text))
      (check (search "EPISODIC MEMORY:" text))
      (check (search "REVISION HISTORY:" text))
      (check (search "KNOWN" text))
      (check (search "CONTENTS" text))
      (check (search "COLOR" text))
      (check (search "BALL-1" text))
      (check (search "OBSERVE" text))
      (check (search "ROOM-1" text)))))

(defun test-show-memory-includes_revision_history ()
  (let ((world (make-world))
        (agent (make-agent)))
    (observe agent world 'room-1)
    (infer agent)
    (add-hypothesis agent '(contents box-1) '(contents box-1 key-1) 0.7)
    (add-hypothesis agent '(contents box-1) '(contents box-1 empty) 0.2)
    (open-container agent world 'box-1)
    (let ((text (let ((*package* (find-package :tiny-brain)))
                  (with-output-to-string (stream)
                    (show-memory agent stream)))))
      (check (search "RETRACTIONS:" text))
      (check (search "CLOSED" text))
      (check (search "OPEN" text))
      (check (search "RESOLVED HYPOTHESES:" text))
      (check (search ":CONFIRMED" text))
      (check (search "KEY-1" text))
      (check (search ":REJECTED" text))
      (check (search "EMPTY" text)))))

(defun run-tests ()
  (setf *failures* 0)
  (test-observing-room-adds-visible-beliefs)
  (test-observing-room-does-not-reveal-closed-container-contents)
  (test-beliefs-have-provenance)
  (test-infer-adds-derived-beliefs)
  (test-inferred-beliefs-explain-their-premises)
  (test-inference-does-not-inspect-ground-truth)
  (test-make-world-accepts-custom-facts)
  (test-define-scenario-builds-scenario-record)
  (test-start-scenario-initializes-agent-and-world)
  (test-load-scenario-reads-example-file)
  (test-validate-scenario-accepts-example-file)
  (test-validate-scenario-reports_unknown_observation)
  (test-validate-scenario-reports_container_errors)
  (test-validate-scenario-reports_goal_and_hypothesis_errors)
  (test-show-validation-prints_issues)
  (test-example-scenarios-have_expected_validation)
  (test-opening-container-requires-access)
  (test-opening-container-reveals-immediate-contents)
  (test-action-observations-have-provenance)
  (test-inference-after-opening-uses-new-beliefs)
  (test-suggest-actions-requires-believed-preconditions)
  (test-suggest-actions-identifies-unknown-reducing-action)
  (test-suggest-actions-disappears-after-unknown-is-resolved)
  (test-exclusive-state-beliefs-retract-conflicts)
  (test-exclusive-state-retraction-is-per-object)
  (test-opening-container-records-retraction)
  (test-explain-direct-observation)
  (test-explain-inference-chain)
  (test-explain-retracted-belief)
  (test-explain-unknown-fact)
  (test-add-goal-records-active-goal)
  (test-known-fact-goal-is-satisfied-by-belief)
  (test-contents-goal-is-satisfied-after-opening-container)
  (test-suggestion-can-serve-active-goal)
  (test-remove-goal)
  (test-select-action-prefers-active-goal)
  (test-select-action-can-pick-curiosity-suggestion)
  (test-perform-suggestion-executes-known-action)
  (test-select-action-returns-nil-without-suggestions)
  (test-plan-for-goal-ready-with-existing-goal)
  (test-plan-for-goal-ready-without-existing-goal)
  (test-plan-for-goal-satisfied)
  (test-plan-for-goal-blocked-without-suggestion)
  (test-show-plan-prints-inspectable-plan)
  (test-step-agent-acts-on-ready-scenario-goal)
  (test-step-agent-reports-satisfied-goal)
  (test-step-agent-reports-blocked-goal)
  (test-step-agent-observes_unobserved_room_for_contents_goal)
  (test-step-agent-can_satisfy_goal_after_observing_remote_room)
  (test-step-agent-can-act-from-curiosity-without-goal)
  (test-show-trace-prints-step_summary)
  (test-show-cognition-prints_brain_centered_cycle)
  (test-observe-records-episode)
  (test-open-container-records-action-episode)
  (test-infer-does-not-record-episode-yet)
  (test-add-hypothesis-records-explicit-uncertainty)
  (test-hypotheses-are-not-beliefs)
  (test-opening-container-confirms-compatible-hypothesis)
  (test-hypothesis-added_after_observation_can_resolve_immediately)
  (test-suggest-tests-identifies_hypothesis_distinguishing_action)
  (test-suggest-tests_requires_competing_active_hypotheses)
  (test-select-action-prefers_goal_and_hypothesis_test)
  (test-select-action-can_prefer_hypothesis_test_without_goal)
  (test-show-memory-groups-current_agent_state)
  (test-show-memory-includes_revision_history)
  (if (zerop *failures*)
      (progn
        (format t "~&All tests passed.~%")
        t)
      (progn
        (format t "~&~D test failure~:P.~%" *failures*)
        (uiop:quit 1))))
