(define-scenario blocked-goal
  :facts ((room lab)
          (room storage)
          (container safe)
          (closed safe)
          (location safe storage))
  :observations (lab)
  :goals ((known (contents safe)))
  :hypotheses (((contents safe)
                (contents safe keycard)
                0.5)
               ((contents safe)
                (contents safe empty)
                0.5)))
