(define-scenario kitchen-box
  :facts ((room kitchen)
          (object apple)
          (color apple green)
          (location apple kitchen)
          (container cabinet)
          (closed cabinet)
          (color cabinet white)
          (location cabinet kitchen)
          (object mug)
          (color mug blue)
          (location mug cabinet))
  :observations (kitchen)
  :goals ((known (contents cabinet)))
  :hypotheses (((contents cabinet)
                (contents cabinet mug)
                0.7)
               ((contents cabinet)
                (contents cabinet empty)
                0.2)
               ((contents cabinet)
                (contents cabinet unknown)
                0.1)))
