(define-scenario lab-crate
  :facts ((room lab)
          (container crate)
          (closed crate)
          (color crate orange)
          (location crate lab)
          (object sensor)
          (shape sensor cube)
          (location sensor crate))
  :observations (lab)
  :goals ((known (contents crate)))
  :hypotheses (((contents crate)
                (contents crate sensor)
                0.6)
               ((contents crate)
                (contents crate empty)
                0.4)))
