(define-scenario nested-containers
  :facts ((room workshop)
          (container chest)
          (closed chest)
          (color chest brown)
          (location chest workshop)
          (container tin)
          (closed tin)
          (color tin silver)
          (location tin chest)
          (object note)
          (location note tin))
  :observations (workshop)
  :goals ((known (contents chest)))
  :hypotheses (((contents chest)
                (contents chest tin)
                0.8)
               ((contents chest)
                (contents chest empty)
                0.2)))
