(defpackage #:tiny-brain
  (:use #:cl)
  (:export
   #:make-world
   #:make-agent
   #:add-belief
   #:observe
   #:infer
   #:open-container
   #:suggest-actions
   #:show-beliefs
   #:why
   #:explain
   #:show-explanation
   #:agent-beliefs
   #:agent-unknowns
   #:agent-retractions
   #:belief
   #:belief-fact
   #:belief-confidence
   #:belief-source
   #:belief-observed-at
   #:belief-rule
   #:belief-premises
   #:rule
   #:rule-name
   #:rule-premises
   #:rule-conclusion
   #:action-suggestion
   #:action-suggestion-action
   #:action-suggestion-target
   #:action-suggestion-reason
   #:action-suggestion-preconditions
   #:retraction
   #:retraction-fact
   #:retraction-reason
   #:retraction-replaced-by
   #:retraction-retracted-at
   #:explanation
   #:explanation-fact
   #:explanation-status
   #:explanation-source
   #:explanation-confidence
   #:explanation-rule
   #:explanation-premises
   #:explanation-retraction))
