(defpackage #:tiny-brain
  (:use #:cl)
  (:export
   #:make-world
   #:make-agent
   #:add-belief
   #:add-goal
   #:add-hypothesis
   #:remove-goal
   #:update-goals
   #:update-hypotheses
   #:observe
   #:infer
   #:open-container
   #:suggest-actions
   #:suggest-tests
   #:select-action
   #:perform-suggestion
   #:show-beliefs
   #:show-goals
   #:show-episodes
   #:show-hypotheses
   #:why
   #:explain
   #:show-explanation
   #:agent-beliefs
   #:agent-unknowns
   #:agent-retractions
   #:agent-goals
   #:agent-episodes
   #:agent-hypotheses
   #:belief
   #:belief-fact
   #:belief-confidence
   #:belief-source
   #:belief-observed-at
   #:belief-rule
   #:belief-premises
   #:rule
   #:rule-name
   #:rule-premises
   #:rule-conclusion
   #:action-suggestion
   #:action-suggestion-action
   #:action-suggestion-target
   #:action-suggestion-reason
   #:action-suggestion-preconditions
   #:action-suggestion-serves-goal
   #:action-suggestion-tests-question
   #:selected-action
   #:selected-action-suggestion
   #:selected-action-reason
   #:episode
   #:episode-type
   #:episode-detail
   #:episode-results
   #:episode-time
   #:hypothesis
   #:hypothesis-question
   #:hypothesis-proposition
   #:hypothesis-confidence
   #:hypothesis-source
   #:hypothesis-status
   #:hypothesis-created-at
   #:hypothesis-resolved-at
   #:goal
   #:goal-desire
   #:goal-status
   #:goal-created-at
   #:goal-satisfied-at
   #:retraction
   #:retraction-fact
   #:retraction-reason
   #:retraction-replaced-by
   #:retraction-retracted-at
   #:explanation
   #:explanation-fact
   #:explanation-status
   #:explanation-source
   #:explanation-confidence
   #:explanation-rule
   #:explanation-premises
   #:explanation-retraction))
